### ISSUE TITLE
the buffer props looks not used

### ISSUE THREAD

**Issue by F4b1n0u** [azuqua/react-dnd-scrollzone#1]
HI,
for my understanding, more the value of the props buffer is high
more we will trigger the scroll earlier right ?
but if I change this value to an other one like with buffer={500}
the scroll start always in the same position of the draggable element

can you help me ?

thanks for this lib by the way ;)

**Comment by nickclaw** [comment]
I'll look into it over the weekend, thanks for the heads up.

**Comment by nickclaw** [comment]
@F4b1n0u Pushed version 2.0.0 to npm with a breaking change.

There's now no more `buffer` property, but you can pass in your own custom strength functions. For your case the migration is like this:

##### Before (v1)
```js
import Scrollzone from 'react-dnd-scrollzone';
const zone = <Scrollzone buffer={500} />;
```

##### After (v2)
```js
import Scrollzone, { createVerticalStrength, createHorizontalStrength } from 'react-dnd-scrollzone';
const vStrength = createVerticalStrength(500);
const hStrength = createHorizontalStrength(500);
const zone = <Scrollzone verticalStrength={vStrength} horizontalStrength={hStrength} />;
```

It's a bit of hassle (sorry about that), but it'll allow much more complex scroll behaviors. 

As to your original issue, the old `buffer` property was respected, but it could have weird behavior if the buffer value was larger than half the width or height of the scroll container. That's been fixed now.

**Comment by nickclaw** [comment]
I'm going to close this now. If you're still having issues after installing the new version, please reopen this with an example.
