### ISSUE TITLE
Does not work with mouse

### ISSUE THREAD

**Issue by arjan** [azuqua/react-dnd-scrollzone#21]
The scrollzone is currently only activated by touch events; it would be nice if it also responds to mouse events.

**Comment by nickclaw** [comment]
Actually it does! It taps into your projects DragDropManager (https://github.com/azuqua/react-dnd-scrollzone/blob/master/src/index.js#L94-L97) for most of the work. So depending on your dnd backend it will hook up to the correct events.

The few touch event listeners you see are just to workaround some browser behavior.

**Comment by arjan** [comment]
Okay, that is weird... because it does not work for me. Will test some more.

**Comment by arjan** [comment]
The exact issue is, that when using the `TouchBackend` using the `{ enableMouseEvents: true }` option, the mouse events do not trigger the scrolling. 
I fixed it by using the HTML5 backend when the mouse is detected, and the TouchBackend otherwise.

**Comment by scriptology** [comment]
it works for me
`export default function getDndContext() {
  if (defaultManager) return defaultManager;
  const isTouchSupported = 'ontouchstart' in window;
  if(isTouchSupported) {
    defaultManager = new DragDropManager(TouchBackend({ enableMouseEvents: true }));
  }
  else {
    defaultManager = new DragDropManager(HTML5Backend);
  }
  return defaultManager;
}`

**Comment by arjan** [comment]
Yes that's how I fixed it in the end.
