### ISSUE TITLE
Scrollzone passes invalid props to child tag

### ISSUE THREAD

**Issue by iChip** [azuqua/react-dnd-scrollzone#3]
return _react2.default.createElement(Tag, _extends({}, this.props, {
        className: compClass,
        onDragOver: this.handleDragOver,
        ref: 'container'
      }));

Leads to:

Warning: Unknown props `tag`, `buffer` on `<div>` tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Scrollzone)

**Comment by nickclaw** [comment]
Thanks for the issue, I'll get a fix in soon. It's not blocking you now is it?

**Comment by D-Manevich** [comment]
Hi, thanks for your module
Unfortunately, I have the same problem with:
``` Warning: Unknown props `verticalStrength`, `horizontalStrength` on <div> tag ```

**Comment by nickclaw** [comment]
Closed again with `v2.0.1`

**Comment by D-Manevich** [comment]
Thank you!
