### ISSUE TITLE
support for touch?

### ISSUE THREAD

**Issue by wan54** [azuqua/react-dnd-scrollzone#6]
I'm this along with https://github.com/yahoo/react-dnd-touch-backend and it doesn't seem to scroll.

Does this actually support touch events?

**Comment by nickclaw** [comment]
It looks like the touch backend doesn't use any of the drag/drop events that this component listens to, so it makes sense that it doesn't work. I do want to support it though -- I'll take a shot at it after this weekend.

**Comment by davidlenthall** [comment]
Any progress on this?

**Comment by ohenrik** [comment]
I hope you get time to take a look at this. I feel like scroll zones are often needed on mobile devices with dnd. So touch support would be really nice.

**Comment by gulderov** [comment]
#13 could solve this

**Comment by nickclaw** [comment]
Thanks for @gulderov for taking the lead on this. I've simplified the logic a bit and plan on releasing this as `v4.0.0` in a couple days. If anyone wants to build the master branch and test it in a more complicated mobile setup I'd appreciate it.

**Comment by jleplomet** [comment]
Is there an update to this issue? Just tested the latest release and touch support is still not working.

**Comment by nickclaw** [comment]
Still in progress, it'll be released as v4.0 when it's ready.

**Comment by nickclaw** [comment]
v4.0.0 is done - let me know how it does!

**Comment by renak** [comment]
I'm using react-dnd-multi-backend to switch back and forth between the html5-backend and touch-backend. I just installed your component and it works great on desktop, but I'm not seeing it work yet on mobile.
