### ISSUE TITLE
Use higher order component pattern for better composition

### ISSUE THREAD

**Issue by jas-per** [azuqua/react-dnd-scrollzone#7]
I tried to combine react-dnd-scrollzone with [react-virtualized](https://github.com/bvaughn/react-virtualized) to improve performance on a huge list (windowed view where only the visible rows are rendered). With the current wrapping behaviour of react-dnd-scrollzone this wasn't possible (using any custom component with tag=component doesn't work atm), so I modified react-dnd-scrollzone to utilize the higher order component pattern (HOC) - works like a charm, PR coming up if you'd like to go that route

**Comment by nickclaw** [comment]
Published as v3.0.0
